CREATE TABLE firewall_request(
	serial_no serial PRIMARY KEY,
	action VARCHAR(255),
	source_hostname VARCHAR(255),
	source_ip VARCHAR(255),
	source_nat_ip VARCHAR(255),
	des_hostname VARCHAR(255),
	des_ip VARCHAR(255),
	des_port VARCHAR(255),
	des_nat_ip VARCHAR(255),
	rule_action VARCHAR(255),
	description VARCHAR(255),
	request_by VARCHAR(255),
	approved_by VARCHAR(255),
	validity VARCHAR(255),
	till_date DATE,
	remarks VARCHAR(255),
	justification VARCHAR(255),
);